// Prepare dist/ for deploy.
//
//   node scripts/publish.mjs        # expects ./dist and ./pdfs
//
// Right now that means one job: copy the two track PDFs into dist/pdfs/ so
// the toolbar's Save PDF button has something to point at. `npm run build`
// alone can't do this — the PDFs are generated by scripts/pdf.mjs into a
// sibling directory that never reaches dist/, and both are gitignored because
// they embed licensed fonts.
//
// Run `npm run ship`, which sequences the whole thing correctly.

import {
  mkdir,
  stat,
  copyFile,
  readdir,
  readFile,
  writeFile,
  rm,
} from "node:fs/promises";
import { createServer } from "node:http";
import { extname } from "node:path";
import puppeteer from "puppeteer";

const root = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const distDir = join(root, "dist");
const pdfDir = join(root, "pdfs");
const lettersDir = join(root, "src", "data", "letters");

// ── Config: keep in sync with src/tracks.ts and scripts/pdf.mjs ────────
// These filenames must match pdfHref() in src/tracks.ts, or the download
// button 404s. All three files derive the same name from the same two parts;
// none of them can import from the others, so they're hand-synced.
const NAME = "Jesse Vaughan";
const PDFS = [
  `${NAME.replace(/\s+/g, "-")}-Resume-Creative-Brand-Leader.pdf`,
  `${NAME.replace(/\s+/g, "-")}-Resume-Engineer-Web-Architect.pdf`,
];
// ───────────────────────────────────────────────────────────────────────

async function ensureDist() {
  try {
    await stat(join(distDir, "index.html"));
  } catch {
    console.error("No dist/index.html found. Run `npm run build` first.");
    process.exit(1);
  }
}

// Only the two track PDFs, named explicitly. Cover letters are generated into
// the same pdfs/ directory and are per-application — copying the directory
// wholesale would publish them to a public URL. Never glob here.
async function copyPdfs() {
  console.log("Copying PDFs into dist:");
  await mkdir(join(distDir, "pdfs"), { recursive: true });
  let ok = true;
  for (const pdf of PDFS) {
    try {
      await copyFile(join(pdfDir, pdf), join(distDir, "pdfs", pdf));
      console.log(`  ✓ ${pdf}`);
    } catch {
      ok = false;
      console.error(`  ✗ ${pdf} not in pdfs/ — Save PDF would 404`);
    }
  }
  return ok;
}

// Which static file each track is snapshotted into. The default track owns
// index.html so the bare URL serves it without a rewrite; the others get their
// own file, which .htaccess maps the clean path onto. `creative.html` exists so
// the alias URL is also a real file rather than only a client-side redirect.
const PRERENDER = [
  { id: "creative", out: ["index.html", "creative.html"] },
  { id: "engineering", out: ["engineering.html"] },
];

const MIME = {
  ".html": "text/html",
  ".js": "text/javascript",
  ".css": "text/css",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".woff2": "font/woff2",
  ".json": "application/json",
};

// Finder writes .DS_Store into any directory you open, including public/,
// and Vite copies public/ into dist/ wholesale — it has no filter for that.
// CI never hits this (Linux, fresh checkout, gitignored), so without this a
// local deploy and a CI deploy would produce different dist/ contents.
async function stripJunk() {
  const entries = await readdir(distDir, { recursive: true });
  const junk = entries.filter((e) => e.endsWith(".DS_Store"));
  for (const file of junk) {
    await rm(join(distDir, file), { force: true });
    console.log(`  ✓ removed ${file}`);
  }
  return junk.length;
}

// ── Prerender ──────────────────────────────────────────────────────────
// This is a Vite SPA, so dist/index.html ships as an empty shell. A human with
// a browser never notices. What does: a recruiter pasting the URL into Slack
// to send to a hiring manager gets an unfurl with no preview, and anything
// fetching without running JS gets a blank page.
//
// Loading each track in the headless Chrome already installed for the PDFs and
// writing what comes back fixes both. The snapshot is markup, not a hydration
// payload — React replaces it on mount. Its only job is to be readable by
// things that never run the script.
function startServer() {
  const server = createServer(async (req, res) => {
    try {
      const pathname = decodeURIComponent(
        new URL(req.url, "http://localhost").pathname,
      );
      const rel =
        pathname === "/" ? "index.html" : pathname.replace(/^\/+/, "");
      const filePath = join(distDir, rel);
      if (!filePath.startsWith(distDir)) return res.writeHead(403).end();
      const body = await readFile(filePath);
      res.writeHead(200, {
        "content-type": MIME[extname(filePath)] ?? "application/octet-stream",
      });
      res.end(body);
    } catch {
      res.writeHead(404).end("Not found");
    }
  });
  return new Promise((r) =>
    server.listen(0, "127.0.0.1", () =>
      r({ server, port: server.address().port }),
    ),
  );
}

async function prerender(port) {
  console.log("\nPrerendering tracks:");
  const browser = await puppeteer.launch({ headless: true });
  try {
    const page = await browser.newPage();
    for (const { id, out } of PRERENDER) {
      // Loaded by ?track=, which useTrack still honours, because this local
      // server has no rewrite rules. On the real host the app reads the path
      // instead and resolves to the same track.
      await page.goto(`http://127.0.0.1:${port}/?track=${id}`, {
        waitUntil: "networkidle0",
      });
      await page.evaluate(async () => {
        await document.fonts.ready;
      });
      const html = await page.content();
      for (const file of out) {
        await writeFile(join(distDir, file), html, "utf8");
        console.log(`  ✓ ${file}`);
      }
    }
  } finally {
    await browser.close();
  }
}

async function verifyHtml() {
  console.log("\nChecking the static HTML carries content:");
  let ok = true;
  for (const { out } of PRERENDER) {
    const file = out[0];
    const html = await readFile(join(distDir, file), "utf8");
    const problems = [];
    if (!html.includes(NAME)) problems.push("name missing from markup");
    if (!/<meta[^>]+property="og:title"/.test(html))
      problems.push("no og:title");
    if (!/<meta[^>]+name="description"/.test(html))
      problems.push("no description");
    if (!/<link[^>]+rel="canonical"/.test(html)) problems.push("no canonical");
    if (html.length < 4000)
      problems.push(`suspiciously small (${html.length}b)`);
    if (problems.length === 0) {
      console.log(`  ✓ ${file}: renders without JS`);
    } else {
      ok = false;
      console.error(`  ✗ ${file}:`);
      for (const p of problems) console.error(`      - ${p}`);
    }
  }
  return ok;
}

// ── Cover-letter guard ─────────────────────────────────────────────────
// Letters are per-application and must never reach the public site. Three
// things already stand between them and dist/: vite.config.ts aliases the
// registry to letters.empty.ts unless INCLUDE_LETTERS=1, `npm run ship`
// rebuilds without it, and copyPdfs() above is an allowlist. This checks the
// output rather than trusting any of them, because all three are things a
// future edit can quietly undo.
//
// On CI none of this can trigger: src/data/letters/ is gitignored, so the
// checkout has no letters and import.meta.glob resolves to nothing. This
// exists for deploys from a laptop that does have them.
async function assertNoLetters() {
  console.log("\nChecking no cover letter reached dist:");
  const problems = [];

  // 1. Nothing in dist/pdfs/ outside the allowlist.
  const shipped = await readdir(join(distDir, "pdfs"));
  for (const file of shipped) {
    if (!PDFS.includes(file))
      problems.push(`dist/pdfs/${file} is not a track PDF`);
  }

  // 2. No letter slug in the JS bundle. Vite inlines the glob's module paths,
  //    so a bundled letter leaves its slug in the output as a literal.
  let slugs = [];
  try {
    slugs = (await readdir(lettersDir))
      .filter((f) => f.endsWith(".ts"))
      .map((f) => f.replace(/\.ts$/, ""));
  } catch {
    slugs = []; // no letters on this machine
  }
  if (slugs.length > 0) {
    const assetDir = join(distDir, "assets");
    const assets = (await readdir(assetDir)).filter((f) => f.endsWith(".js"));
    for (const asset of assets) {
      const js = await readFile(join(assetDir, asset), "utf8");
      for (const slug of slugs) {
        if (js.includes(`letters/${slug}`)) {
          problems.push(`letter "${slug}" is bundled into assets/${asset}`);
        }
      }
    }
  }

  if (problems.length === 0) {
    console.log(
      slugs.length > 0
        ? `  ✓ ${slugs.length} local letter(s), none in dist`
        : "  ✓ clean",
    );
    return true;
  }
  for (const p of problems) console.error(`  ✗ ${p}`);
  return false;
}

await ensureDist();
console.log(`Cleaning dist:`);
const removed = await stripJunk();
if (removed === 0) console.log("  ✓ nothing to remove");
const copied = await copyPdfs();
const { server, port } = await startServer();
try {
  await prerender(port);
} finally {
  server.close();
}
const rendered = await verifyHtml();
const clean = await assertNoLetters();
const ok = copied && rendered && clean;
console.log(ok ? "\ndist/ ready to deploy." : "\nFAILED — see above.");
process.exit(ok ? 0 : 1);
