// Prepare dist/ for deploy.
//
//   node scripts/publish.mjs        # expects ./dist and ./pdfs
//
// Right now that means one job: copy the two track PDFs into dist/pdfs/ so
// the toolbar's Save PDF button has something to point at. `npm run build`
// alone can't do this — the PDFs are generated by scripts/pdf.mjs into a
// sibling directory that never reaches dist/, and both are gitignored because
// they embed licensed fonts.
//
// Run `npm run ship`, which sequences the whole thing correctly.

import { mkdir, stat, copyFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const distDir = join(root, "dist");
const pdfDir = join(root, "pdfs");

// ── Config: keep in sync with src/tracks.ts and scripts/pdf.mjs ────────
// These filenames must match pdfHref() in src/tracks.ts, or the download
// button 404s. All three files derive the same name from the same two parts;
// none of them can import from the others, so they're hand-synced.
const NAME = "Jesse Vaughan";
const PDFS = [
  `${NAME.replace(/\s+/g, "-")}-Resume-Creative-Brand-Leader.pdf`,
  `${NAME.replace(/\s+/g, "-")}-Resume-Engineer-Web-Architect.pdf`,
];
// ───────────────────────────────────────────────────────────────────────

async function ensureDist() {
  try {
    await stat(join(distDir, "index.html"));
  } catch {
    console.error("No dist/index.html found. Run `npm run build` first.");
    process.exit(1);
  }
}

// Only the two track PDFs, named explicitly. Cover letters are generated into
// the same pdfs/ directory and are per-application — copying the directory
// wholesale would publish them to a public URL. Never glob here.
async function copyPdfs() {
  console.log("Copying PDFs into dist:");
  await mkdir(join(distDir, "pdfs"), { recursive: true });
  let ok = true;
  for (const pdf of PDFS) {
    try {
      await copyFile(join(pdfDir, pdf), join(distDir, "pdfs", pdf));
      console.log(`  ✓ ${pdf}`);
    } catch {
      ok = false;
      console.error(`  ✗ ${pdf} not in pdfs/ — Save PDF would 404`);
    }
  }
  return ok;
}

await ensureDist();
const ok = await copyPdfs();
console.log(
  ok ? "\ndist/ ready to deploy." : "\nFAILED — run `npm run pdf` first.",
);
process.exit(ok ? 0 : 1);
