// Prepare dist/ for deploy.
//
//   node scripts/publish.mjs        # expects ./dist and ./pdfs
//
// Right now that means one job: copy the two track PDFs into dist/pdfs/ so
// the toolbar's Save PDF button has something to point at. `npm run build`
// alone can't do this — the PDFs are generated by scripts/pdf.mjs into a
// sibling directory that never reaches dist/, and both are gitignored because
// they embed licensed fonts.
//
// Run `npm run ship`, which sequences the whole thing correctly.

import { mkdir, stat, copyFile, readdir, readFile, rm } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const distDir = join(root, "dist");
const pdfDir = join(root, "pdfs");
const lettersDir = join(root, "src", "data", "letters");

// ── Config: keep in sync with src/tracks.ts and scripts/pdf.mjs ────────
// These filenames must match pdfHref() in src/tracks.ts, or the download
// button 404s. All three files derive the same name from the same two parts;
// none of them can import from the others, so they're hand-synced.
const NAME = "Jesse Vaughan";
const PDFS = [
  `${NAME.replace(/\s+/g, "-")}-Resume-Creative-Brand-Leader.pdf`,
  `${NAME.replace(/\s+/g, "-")}-Resume-Engineer-Web-Architect.pdf`,
];
// ───────────────────────────────────────────────────────────────────────

async function ensureDist() {
  try {
    await stat(join(distDir, "index.html"));
  } catch {
    console.error("No dist/index.html found. Run `npm run build` first.");
    process.exit(1);
  }
}

// Only the two track PDFs, named explicitly. Cover letters are generated into
// the same pdfs/ directory and are per-application — copying the directory
// wholesale would publish them to a public URL. Never glob here.
async function copyPdfs() {
  console.log("Copying PDFs into dist:");
  await mkdir(join(distDir, "pdfs"), { recursive: true });
  let ok = true;
  for (const pdf of PDFS) {
    try {
      await copyFile(join(pdfDir, pdf), join(distDir, "pdfs", pdf));
      console.log(`  ✓ ${pdf}`);
    } catch {
      ok = false;
      console.error(`  ✗ ${pdf} not in pdfs/ — Save PDF would 404`);
    }
  }
  return ok;
}

// Finder writes .DS_Store into any directory you open, including public/,
// and Vite copies public/ into dist/ wholesale — it has no filter for that.
// CI never hits this (Linux, fresh checkout, gitignored), so without this a
// local deploy and a CI deploy would produce different dist/ contents.
async function stripJunk() {
  const entries = await readdir(distDir, { recursive: true });
  const junk = entries.filter((e) => e.endsWith(".DS_Store"));
  for (const file of junk) {
    await rm(join(distDir, file), { force: true });
    console.log(`  ✓ removed ${file}`);
  }
  return junk.length;
}

// ── Cover-letter guard ─────────────────────────────────────────────────
// Letters are per-application and must never reach the public site. Three
// things already stand between them and dist/: vite.config.ts aliases the
// registry to letters.empty.ts unless INCLUDE_LETTERS=1, `npm run ship`
// rebuilds without it, and copyPdfs() above is an allowlist. This checks the
// output rather than trusting any of them, because all three are things a
// future edit can quietly undo.
//
// On CI none of this can trigger: src/data/letters/ is gitignored, so the
// checkout has no letters and import.meta.glob resolves to nothing. This
// exists for deploys from a laptop that does have them.
async function assertNoLetters() {
  console.log("\nChecking no cover letter reached dist:");
  const problems = [];

  // 1. Nothing in dist/pdfs/ outside the allowlist.
  const shipped = await readdir(join(distDir, "pdfs"));
  for (const file of shipped) {
    if (!PDFS.includes(file))
      problems.push(`dist/pdfs/${file} is not a track PDF`);
  }

  // 2. No letter slug in the JS bundle. Vite inlines the glob's module paths,
  //    so a bundled letter leaves its slug in the output as a literal.
  let slugs = [];
  try {
    slugs = (await readdir(lettersDir))
      .filter((f) => f.endsWith(".ts"))
      .map((f) => f.replace(/\.ts$/, ""));
  } catch {
    slugs = []; // no letters on this machine
  }
  if (slugs.length > 0) {
    const assetDir = join(distDir, "assets");
    const assets = (await readdir(assetDir)).filter((f) => f.endsWith(".js"));
    for (const asset of assets) {
      const js = await readFile(join(assetDir, asset), "utf8");
      for (const slug of slugs) {
        if (js.includes(`letters/${slug}`)) {
          problems.push(`letter "${slug}" is bundled into assets/${asset}`);
        }
      }
    }
  }

  if (problems.length === 0) {
    console.log(
      slugs.length > 0
        ? `  ✓ ${slugs.length} local letter(s), none in dist`
        : "  ✓ clean",
    );
    return true;
  }
  for (const p of problems) console.error(`  ✗ ${p}`);
  return false;
}

await ensureDist();
console.log(`Cleaning dist:`);
const removed = await stripJunk();
if (removed === 0) console.log("  ✓ nothing to remove");
const copied = await copyPdfs();
const clean = await assertNoLetters();
const ok = copied && clean;
console.log(ok ? "\ndist/ ready to deploy." : "\nFAILED — see above.");
process.exit(ok ? 0 : 1);
